---
name: Build Artifacts

on:
  workflow_dispatch:
    inputs:
      registry:
        type: choice
        description: "registry to push images to (ghcr.io,docker.io)"
        options:
          - 'ghcr.io,docker.io'
          - 'ghcr.io'
          - 'docker.io'
          
          
  # push:
  #   branches:
  #   - '**'
  #   paths-ignore:
  #   - '.github/**'
  #   - 'docs/**'
  #   - 'CODE-OF-CONDUCT.md'
  #   - 'CONTRIBUTING.md'
  #   - 'LICENSE'
  #   - 'README.md'
  #   - 'SECURITY.md'

concurrency:
  group: ${{ format('test-build-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
        - name: jaeger-integration-tests
          file: integration-tests/Dockerfile
          context: integration-tests
        - name: jaeger-readiness-probe
          file: readiness-probe/Dockerfile
          context: readiness-probe
        - name: jaeger-transfer
          file: docker-transfer/Dockerfile
          context: ""
    runs-on: ubuntu-latest
    name: ${{ matrix.component.name }}
    permissions:
      contents: read
      packages: write
    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v3
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: testpatchesorg/qubership-workflow-hub/actions/docker-action@docker-action
      with:
        # ref: v${{ inputs.version }}
        download-artifact: false
        #dry-run: ${{ inputs.dry-run }}
        component: ${{ toJson(matrix.component) }}
        platforms: linux/amd64
        registry: ${{ inputs.registry }}
        docker-io-login: ${{ vars.DOCKERHUB_USER }}
        docker-io-token: ${{ secrets.DOCKERHUB_RW_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
